### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#16]
## Begin Telling People Release

- [x] Battle stats for players
- [x] Leaderbaords
- [x] Can select map and game mode when creating new room
- [x] Game has smooth gameplay
- [x] Convert front facing site to VueJS 

## Full Release

- [x] Add the map upload form
- [ ] Add character with flamethrower weapon
- [ ] Add character with grenade launcher weapon
- [ ] Add character with sustained beam laser rifle weapon and bounces off walls
- [ ] Build game modes

## Steam, Tablet, iPhone, and Android Release

- [ ] Build electron shell
- [ ] Build Android shell
- [ ] Build iPhone shell
- [ ] Begin the Steam GreenLight process

## Store Goals
- [ ] Character skins
- [ ] Jet pack trail skins
- [ ] HUD skins
- [ ] Gun skins

First skins will cost 300
Premium skins will range between 400 and 3000

1. 500 - $4.99
2. 1200 - $9.99
3. 2500 - $19.99
4. 6500 - $49.99
5. 14000 - $99.99

![clash-of-clans-buy-gems-worldwide](https://cloud.githubusercontent.com/assets/8272012/21783579/d9ea2fea-d66c-11e6-98cb-9f7c3cf1d97f.jpg)

Home page `/`
![screen shot 2017-01-09 at 1 08 08 pm](https://cloud.githubusercontent.com/assets/8272012/21783590/eb90ae68-d66c-11e6-983c-6ba9003b4408.png)

![screen shot 2017-01-15 at 3 38 54 pm](https://cloud.githubusercontent.com/assets/8272012/21967288/c74b074e-db38-11e6-9af2-e00bd7140082.png)

Store page `/store`
![screen shot 2017-01-09 at 1 08 13 pm](https://cloud.githubusercontent.com/assets/8272012/21783592/ef9727e4-d66c-11e6-97e5-d5c6f5544fa9.png)

**Comment by michaeljcalkins** [comment]
Notes from the wunderlist task, I don't really agree with this anymore:
Sell extra skins on top of this via a currency that is earned by killing enemies.

When you have enough currency you can unlock a skin.

**Comment by michaeljcalkins** [comment]
Yes (skins, hurt border, etc.) and ranking for players
I'd like to offer the game for $10 - $15 and just unlock everything
Ads for free players on respawn modal

**Comment by michaeljcalkins** [comment]
The only premium features I want to build are extra character classes that add strategy to the game.

"Does this user have access to the flamethrower?"
Yes: if the flag on their account is true
No: open a window that lets them pay and update their account to true

Then just work on building better maps and gamemodes.
$3 per class or something like that.

**Comment by michaeljcalkins** [comment]
"Thanks for trying out Ranger Steve!"

Pop up every 2 - 5 minutes with buy buttons above the leaderboard and on respawn modal and on homepage.

![](http://4.bp.blogspot.com/-ojAE-UaQv3w/UqDG5vAmeOI/AAAAAAAABYI/mB7le-ughNs/s1600/Screen+Shot+2013-12-05+at+11.29.21+AM.png)

**Comment by And-re** [comment]
maybe not every 2 - 5 minutes but just after every map

**Comment by michaeljcalkins** [comment]
1. Before you start playing
2. At the end of every round or have the buy now button in the End of Round modal
3. "Buy Now" above the leaderboards
4. "Buy Now" on the respawn modal

All premium players have a 👑  next to their names (like twitch)

**Comment by michaeljcalkins** [comment]
![screencapture-barracks-icombat-com-tactical-player-achievements-86891-1466007252083](https://cloud.githubusercontent.com/assets/8272012/18684587/92df47c4-7f29-11e6-8cf4-6146a466f534.png)
![screencapture-barracks-icombat-com-tactical-player-matches-86891-1466007268827](https://cloud.githubusercontent.com/assets/8272012/18684590/92e29244-7f29-11e6-8e25-065c592dfb1c.png)
![screencapture-barracks-icombat-com-tactical-player-overview-1466007223246](https://cloud.githubusercontent.com/assets/8272012/18684591/92e3c0a6-7f29-11e6-8e7a-c13beb845a9b.png)
![screencapture-barracks-icombat-com-tactical-player-timeline-1466007199946](https://cloud.githubusercontent.com/assets/8272012/18684589/92e15366-7f29-11e6-955a-fce6708615fc.png)
![screencapture-barracks-icombat-com-tactical-player-weapons-86891-1466007234479](https://cloud.githubusercontent.com/assets/8272012/18684588/92df8810-7f29-11e6-937c-4094685d8a57.png)

![screen shot 2016-06-15 at 7 10 30 am](https://cloud.githubusercontent.com/assets/8272012/18684677/db635d64-7f29-11e6-917d-2f65c9bc9289.png)
![screen shot 2016-06-15 at 8 59 15 am](https://cloud.githubusercontent.com/assets/8272012/18684678/db77e888-7f29-11e6-9e57-ee02dc132b05.png)
![screen shot 2016-06-15 at 9 19 59 am](https://cloud.githubusercontent.com/assets/8272012/18684679/db7d47b0-7f29-11e6-9027-4e4611cec64a.png)

Potential open beta:
One map, two or three guns

**Comment by michaeljcalkins** [comment]
![screen shot 2017-01-10 at 10 21 10 pm](https://cloud.githubusercontent.com/assets/8272012/21837777/279d2316-d783-11e6-9c0c-22292dd8cfde.png)
![screen shot 2017-01-10 at 10 21 05 pm](https://cloud.githubusercontent.com/assets/8272012/21837779/27a03074-d783-11e6-86fd-3a22bea529f9.png)
![screen shot 2017-01-10 at 10 21 01 pm](https://cloud.githubusercontent.com/assets/8272012/21837778/279e8882-d783-11e6-94fc-5ba1537263bc.png)

**Comment by michaeljcalkins** [comment]
@And-re Initial updates in preparation for the store.

**Comment by michaeljcalkins** [comment]
![screen shot 2017-01-10 at 10 46 44 pm](https://cloud.githubusercontent.com/assets/8272012/21838405/af06fbbc-d786-11e6-8c7e-201e305531b2.png)

**Comment by michaeljcalkins** [comment]
![img_0023](https://cloud.githubusercontent.com/assets/8272012/22172932/919785c6-df68-11e6-9d28-03a594966170.PNG)
![img_0024](https://cloud.githubusercontent.com/assets/8272012/22172935/91badcd8-df68-11e6-8cd0-09ba19dc0f36.PNG)
![img_0025](https://cloud.githubusercontent.com/assets/8272012/22172934/91b7f612-df68-11e6-9e37-2ab636880daf.PNG)
![img_0026](https://cloud.githubusercontent.com/assets/8272012/22172933/91b7b4e0-df68-11e6-810e-acc582665a20.PNG)

**Comment by michaeljcalkins** [comment]
![pvp net_riot_store_05](https://cloud.githubusercontent.com/assets/8272012/22184786/45d14b64-e08e-11e6-8b9e-68fdf0833c87.jpg)
![pvp net_riot_store_01](https://cloud.githubusercontent.com/assets/8272012/22184787/45d26058-e08e-11e6-8142-6b78f5c046ad.jpg)
![exploit-in-league-of-legends-allows-access-to-the-store-from-web-browser-471979-2](https://cloud.githubusercontent.com/assets/8272012/22184788/45d2a50e-e08e-11e6-9eac-a47de0ac391c.jpg)
