### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#213]
# Game Developer

- [ ] Build leaderboards
- [ ] Build battle stats
- [ ] Build character store
- [ ] Build game modes
- [ ] Add joystick and fire button so non computer people can play
- [ ] Add character with flamethrower weapon
- [ ] Add character with grenade launcher weapon

# Asset Developer

- [ ] Convert HighRuleJungle to 32x32
- [ ] Fix HighRuleJungle to use a Hi Res background
- [ ] Add roof to the DarkForest
- [ ] Redesign PunkFallout using the Future Punk Tileset (Make similar in size to HighRuleJungle
- [ ] Three maps per game mode
- [ ] Manage the community map contributions
- [ ] Create 12 sprites out of all the player bodies for the character store
- [ ] New promo video https://youtu.be/aBTtJ_JVQ5c
